In [2]:
import numpy as np
import pandas as pd


In [3]:
#performing PCA
df = pd.read_csv("StudentsPerformance.csv")
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [4]:
df = df  - df.mean() #step 1 : normalization 

In [5]:
covariance_matrix = df.cov() #step 2 : covariance matrix
covariance_matrix

math score  reading score  writing score
math score     229.918998     180.998958     184.939133
reading score  180.998958     213.165605     211.786661
writing score  184.939133     211.786661     230.907992

In [6]:
eig_values, eig_vectors = np.linalg.eig(covariance_matrix) # step 3 : generating eigen values and eigen vectors

In [7]:
print(eig_values, eig_vectors) #find the eigen value with max magnitude

[610.12126748  53.91836027   9.95296685] [[ 0.56264911  0.82561176  0.04232262]
 [ 0.57397682 -0.35329218 -0.73873896]
 [ 0.59495932 -0.43994302  0.67266154]]


In [9]:
e_indices = np.argsort(eig_values)[::-1] #sorting the eigen values in descending order
eig_values = eig_values[e_indices]
eig_vectors = eig_vectors[:,e_indices]
eig_vectors #reprojections of the original data


array([[ 0.56264911,  0.82561176,  0.04232262],
       [ 0.57397682, -0.35329218, -0.73873896],
       [ 0.59495932, -0.43994302,  0.67266154]])